### PR TITLE
Workaround for tss-lib PreParams generation on machines with < 3 CPU

### LINKED ISSUE #289: Investigate context deadline exceeded in TestGenerateKeyAndSign
`TestGenerateKeyAndSign` fails from time to time in CI with `context deadline exceeded`.
It looks like it hangs after `keygen round 3 started`. It doesn't seem that the timeout (60 s) is too low, as nothing is logged just after 4 seconds of test execution.
This issue aims at a close investigation of the problem, especially the synchronization of members and networking.

```
16:04:34.728  INFO   keep-tss: starting announce protocol protocol_announce.go:23
16:04:34.728  INFO   keep-tss: starting announce protocol protocol_announce.go:23
16:04:34.728  INFO   keep-tss: starting announce protocol protocol_announce.go:23
16:04:34.728  INFO   keep-tss: announce protocol completed successfully protocol_announce.go:92
16:04:35.728  INFO   keep-tss: announce protocol completed successfully protocol_announce.go:92
16:04:35.728  INFO   keep-tss: announce protocol completed successfully protocol_announce.go:92
16:04:36.748  INFO   keep-tss: [party:{3,}]: initialized key generation tss.go:98
16:04:36.748  INFO   keep-tss: [party:{0,}]: initialized key generation tss.go:98
16:04:36.748  INFO   keep-tss: [party:{2,}]: initialized key generation tss.go:98
16:04:36.748  INFO   keep-tss: [party:{4,}]: initialized key generation tss.go:98
16:04:36.748  INFO   keep-tss: [party:{1,}]: initialized key generation tss.go:98
16:04:36.749  INFO   keep-tss: [party:{3,}]: starting key generation tss.go:109
16:04:36.749  INFO    tss-lib: party {3,}: keygen round 1 starting party.go:135
16:04:37.748  INFO   keep-tss: [party:{0,}]: starting key generation tss.go:109
16:04:37.748  INFO    tss-lib: party {0,}: keygen round 1 starting party.go:135
16:04:37.749  INFO   keep-tss: [party:{1,}]: starting key generation tss.go:109
16:04:37.749  INFO    tss-lib: party {1,}: keygen round 1 starting party.go:135
16:04:37.750  INFO   keep-tss: [party:{2,}]: starting key generation tss.go:109
16:04:37.750  INFO    tss-lib: party {2,}: keygen round 1 starting party.go:135
16:04:37.750  INFO   keep-tss: [party:{4,}]: starting key generation tss.go:109
16:04:37.750  INFO    tss-lib: party {4,}: keygen round 1 starting party.go:135
16:04:37.751  INFO    tss-lib: party {4,}: keygen round 2 started party.go:172
16:04:37.752  INFO    tss-lib: party {0,}: keygen round 2 started party.go:172
16:04:37.752  INFO    tss-lib: party {1,}: keygen round 2 started party.go:172
16:04:37.752  INFO    tss-lib: party {2,}: keygen round 2 started party.go:172
16:04:37.752  INFO    tss-lib: party {3,}: keygen round 2 started party.go:172
16:04:38.410  INFO    tss-lib: party {2,}: keygen round 3 started party.go:172
16:04:38.410  INFO    tss-lib: party {3,}: keygen round 3 started party.go:172
16:04:38.518  INFO    tss-lib: party {1,}: keygen round 3 started party.go:172
16:04:38.551  INFO    tss-lib: party {4,}: keygen round 3 started party.go:172
--- FAIL: TestGenerateKeyAndSign (60.00s)
    tss_test.go:115: context deadline exceeded
```

Example failed Circle CI jobs:
* https://circleci.com/gh/keep-network/keep-tecdsa/4725
* https://circleci.com/gh/keep-network/keep-tecdsa/5027
* https://circleci.com/gh/keep-network/keep-tecdsa/4725

### PR DESCRIPTION
**Pull request by nkuba**
We used to call `GeneratePreParams` function without `optionalConcurrency` parameter. 
In such a case, the library gets a number of CPUs to calculate a number of goroutines to run. Unfortunately, the library is dividing the number by `3` which on machines with less than 3 CPUs causes execution of `0` goroutines, so the generation fails with a timeout while waiting for numbers generation. 

The problem has been reported in https://github.com/binance-chain/tss-lib/issues/93

As a workaround, we are providing the `optionalConcurrency` parameter with fixed value `3` so the further calculations hold.

Additionally, closes #289

### CODE REVIEW

File: pkg/ecdsa/tss/keygen.go [hunk 1]
```diff
@@ -18,10 +18,13 @@ const (
...
-// TODO: Consider pre-generating parameters to a pool and use them on protocol
-// start.
 func GenerateTSSPreParams() (*keygen.LocalPreParams, error) {
-	preParams, err := keygen.GeneratePreParams(preParamsGenerationTimeout)
+	// As a workaround for a bug in tss-lib we have to provide `optionalConcurrency`
+	// parameter with value of at least `3` so the underlying goroutines are
+	// executed on machines with less than 3 CPU.
+	//
+	// See: https://github.com/binance-chain/tss-lib/issues/93
+	preParams, err := keygen.GeneratePreParams(preParamsGenerationTimeout, 3)
```
Comment (pdyraga) [inline pkg/ecdsa/tss/keygen.go]: Why don't we make it configurable? With hardcoded `3`, even if I want to dedicate more nodes, I cannot. 
I understand there is a bug in `tss-lib` so maybe we could add a reference to issue 93 in the sample config, explain this parameter does not reflect the number of CPUs but is used as `concurrency / 3 * 2` and let operator to decide?

**Comment by pdyraga** [comment]
Closes #289 :tada:
