### PR TITLE
Fail Fast With Bad BTC Configuration

### LINKED ISSUE #807: Clients that are not configured for liquidation recovery are starting the process errors loop
I've got three clients that have an old configuration file, any liquidation recovery configuration is not present.
When a deposit started liquidation the clients started recovery and are reporting bitcoin address resolution failures.
```
2021-06-03T12:36:29.149+0200	ERROR	keep-ecdsa	failed to resolve a btc address for keep: [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] address: [] err: [insufficient length for public key ]
```

I expect that if the configuration is missing in the file the client won't start the recovery process. It could be enough if the client logs a warning message after it picks up a keep termination event about missing configuration and does not invoke the whole process.

Tested on branch `liquidation-recovery-integration`.

<details>
<summary>Debug logs</summary>

```
2021-06-03T12:35:53.121+0200	WARN	keep-ecdsa	keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] terminated event received at block [42356]
2021-06-03T12:35:53.121+0200	INFO	keep-ethlike	waiting for block [42368] to confirm chain state
2021-06-03T12:36:29.119+0200	INFO	keep-tss	announcing presence
2021-06-03T12:36:29.138+0200	INFO	keep-tss	member [0xB7021acafEcf289Fa345ecc95EcAb18077530841] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:29.140+0200	INFO	keep-tss	member [0x65849fc91F8289b401e9d8F6D306b814B7F055C3] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:29.149+0200	INFO	keep-tss	member [0x28BcFAD75ee4c87B9089ba4c03a79B8148104Da4] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:29.149+0200	INFO	keep-tss	announce protocol completed successfully
2021-06-03T12:36:29.149+0200	ERROR	keep-ecdsa	failed to resolve a btc address for keep: [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] address: [] err: [insufficient length for public key ]
2021-06-03T12:36:30.151+0200	INFO	keep-ethlike	waiting for block [42368] to confirm chain state
2021-06-03T12:36:30.159+0200	INFO	keep-tss	announcing presence
2021-06-03T12:36:30.163+0200	INFO	keep-tss	member [0xB7021acafEcf289Fa345ecc95EcAb18077530841] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:30.166+0200	INFO	keep-tss	member [0x65849fc91F8289b401e9d8F6D306b814B7F055C3] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:30.171+0200	INFO	keep-tss	member [0x28BcFAD75ee4c87B9089ba4c03a79B8148104Da4] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:30.171+0200	INFO	keep-tss	announce protocol completed successfully
2021-06-03T12:36:30.171+0200	ERROR	keep-ecdsa	failed to resolve a btc address for keep: [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] address: [] err: [insufficient length for public key ]
2021-06-03T12:36:32.234+0200	INFO	keep-ethlike	waiting for block [42368] to confirm chain state
2021-06-03T12:36:32.239+0200	INFO	keep-tss	announcing presence
2021-06-03T12:36:32.240+0200	INFO	keep-tss	member [0xB7021acafEcf289Fa345ecc95EcAb18077530841] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:32.319+0200	INFO	keep-tss	member [0x28BcFAD75ee4c87B9089ba4c03a79B8148104Da4] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:32.371+0200	INFO	keep-tss	member [0x65849fc91F8289b401e9d8F6D306b814B7F055C3] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:32.371+0200	INFO	keep-tss	announce protocol completed successfully
2021-06-03T12:36:32.371+0200	ERROR	keep-ecdsa	failed to resolve a btc address for keep: [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] address: [] err: [insufficient length for public key ]
2021-06-03T12:36:36.879+0200	INFO	keep-ethlike	waiting for block [42368] to confirm chain state
2021-06-03T12:36:36.919+0200	INFO	keep-tss	announcing presence
2021-06-03T12:36:36.923+0200	INFO	keep-tss	member [0xB7021acafEcf289Fa345ecc95EcAb18077530841] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:37.020+0200	INFO	keep-tss	member [0x28BcFAD75ee4c87B9089ba4c03a79B8148104Da4] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:37.122+0200	INFO	keep-tss	member [0x65849fc91F8289b401e9d8F6D306b814B7F055C3] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:37.122+0200	INFO	keep-tss	announce protocol completed successfully
2021-06-03T12:36:37.122+0200	ERROR	keep-ecdsa	failed to resolve a btc address for keep: [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] address: [] err: [insufficient length for public key ]
2021-06-03T12:36:43.660+0200	INFO	keep-net-libp2p	number of connected peers: [2]
2021-06-03T12:36:46.897+0200	INFO	keep-ethlike	waiting for block [42368] to confirm chain state
2021-06-03T12:36:46.921+0200	INFO	keep-tss	announcing presence
2021-06-03T12:36:46.922+0200	INFO	keep-tss	member [0xB7021acafEcf289Fa345ecc95EcAb18077530841] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:47.335+0200	INFO	keep-tss	member [0x28BcFAD75ee4c87B9089ba4c03a79B8148104Da4] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:47.366+0200	INFO	keep-tss	member [0x65849fc91F8289b401e9d8F6D306b814B7F055C3] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:36:47.366+0200	INFO	keep-tss	announce protocol completed successfully
2021-06-03T12:36:47.366+0200	ERROR	keep-ecdsa	failed to resolve a btc address for keep: [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] address: [] err: [insufficient length for public key ]
2021-06-03T12:37:08.483+0200	INFO	keep-ethlike	waiting for block [42368] to confirm chain state
2021-06-03T12:37:08.489+0200	INFO	keep-tss	announcing presence
2021-06-03T12:37:08.490+0200	INFO	keep-tss	member [0xB7021acafEcf289Fa345ecc95EcAb18077530841] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
2021-06-03T12:37:08.605+0200	INFO	keep-tss	member [0x65849fc91F8289b401e9d8F6D306b814B7F055C3] from keep [0x475A49976Dd146D35c704E248F4F5ce6FeE971bf] announced its presence
...
```

</details>

### PR DESCRIPTION
**Pull request by beaushinkle**
If a user has not configured `Extensions.TBTC.Bitcoin` with the required fields (BeneficiaryAddress and BitcoinChainName presently), this PR changes the client behavior in the following ways:

* We warn at startup about the paths that are missing, and suggest possible values:
```
2021-06-04T11:11:26.586-0400    WARN    keep-cmd        invalid Bitcoin configuration: [a bit
coin address or extended public key (*pub) is required; configure one at [Extensions.TBTC.Bitc
oin.BeneficiaryAddress]]
2021-06-04T11:11:26.586-0400    WARN    keep-cmd        invalid Bitcoin configuration: [a valid chain name is required; choose between [mainnet, regtest, simnet, testnet3] and configure it at [Extensions.TBTC.Bitcoin.BitcoinChainName]: [unable to find chaincfg param for name: [banana]]]
```

* We error out and skip the retry loop during termination handling:
```
2021-06-04T10:29:13.005-0400    ERROR    keep-ecdsa    failed to broadcast the bitcoin recovery transaction: [a bitcoin address or extended public key (*pub) is required; configure one at [Extensions.TBTC.Bitcoin.BeneficiaryAddress]]
2021-06-04T10:29:13.005-0400    ERROR    keep-ecdsa    failed to broadcast the bitcoin recovery transaction: [a valid chain name is required; choose between [mainnet, regtest, simnet, testnet3] and configure it at [Extensions.TBTC.Bitcoin.BitcoinChainName]: [unable to find chaincfg param for name: [banana]]]
```

closes #807 

tagging @nkuba for review

### CODE REVIEW

File: cmd/start.go [hunk 1]
```diff
@@ -140,6 +140,11 @@ func Start(c *cli.Context) error {
 		return err
 	}
 
+	err = config.Extensions.TBTC.Bitcoin.Validate()
+	if err != nil {
+		logger.Warnf("invalid Bitcoin configuration: [%v]", err)
```
Comment (nkuba) [inline cmd/start.go:145]:
```suggestion
		logger.Warnf("invalid bitcoin configuration for tbtc extenstion: [%v]", err)
```

File: pkg/chain/bitcoin/config.go [hunk 2]
```diff
@@ -14,6 +14,19 @@ type Config struct {
...
+// and an error detailing what went wrong if not.
+func (c Config) Validate() error {
+	if c.BeneficiaryAddress == "" {
+		return fmt.Errorf("a bitcoin address or extended public key (*pub) is required; configure one at [Extensions.TBTC.Bitcoin.BeneficiaryAddress]")
+	}
+	_, err := c.ChainParams()
+	if err != nil {
+		return fmt.Errorf("a valid chain name is required; choose between [mainnet, regtest, simnet, testnet3] and configure it at [Extensions.TBTC.Bitcoin.BitcoinChainName]: [%v]", err)
+	}
+	return nil
```
Comment (nkuba) [inline pkg/chain/bitcoin/config.go:27]: If `BeneficiaryAddress` is a bitcoin address, how hard would it be to add a validation that it's valid for the given chain name?

File: pkg/client/client.go [hunk 3]
```diff
@@ -988,184 +988,187 @@ func monitorKeepTerminatedEvent(
...
-							},
-						)
-						if err != nil {
-							logger.Errorf(
-								"failed to confirm keep [%s] termination: [%v]",
-								keep.ID(),
-								err,
+				err := tbtcConfig.Bitcoin.Validate()
+				if err == nil {
+					err = utils.DoWithDefaultRetry(
```
Comment (nkuba) [inline pkg/client/client.go:993]:
```suggestion
				if err != nil {
					logger.Errorf("failed to handle KeepTerminatedEvent due to invalid bitcoin configuration for tbtc extension: [%v]", err)
					return
				}
				
				err = utils.DoWithDefaultRetry(
```

**Comment by beaushinkle** [comment]
Okay, I ended up moving some stuff around to accommodate address validation. The code that did address derivation lived in recovery, which depends on bitcoin. If I want to pull that in for the bitcoin validation code, I'd create a circular dependency. To resolve that, I moved the derivation code to the bitcoin project.

I'm not done writing tests for the validate code yet, but I figured I'd push what I had so that you could review while our timezones aren't overlapping. Cheers!

File: cmd/start.go [hunk 4]
```diff
@@ -140,6 +140,11 @@ func Start(c *cli.Context) error {
 		return err
 	}
 
+	err = config.Extensions.TBTC.Bitcoin.Validate()
+	if err != nil {
+		logger.Warnf("invalid bitcoin configuration for tbtc extension: [%v]", err)
+	}
```
Comment (nkuba) [inline cmd/start.go:146]: What if we cover two possible situations differently:
1. `Extensions.TBTC.Bitcoin` configuration is not provided --> we log a warning and the client starts (backward compatibility).
2. `Extensions.TBTC.Bitcoin` configuration is provided but is invalid --> we return an error so the client won't start

For the second case, we could also just log an error and let the client start, the client will possibly fail a recovery if liquidation happens in the future.

I'd like to ask @Shadowfiend for his opinion too.

Comment (beaushinkle) [reply cmd/start.go]: Okay - implemented this idea in 4bdbc63. I'm not in love with *how* it's done, so if you have a more elegant way I'm all ears!

Comment (nkuba) [reply cmd/start.go]: What if we use `(bitcoin.Config{}) == config.Extensions.TBTC.Bitcoin`?
```go
err := config.Extensions.TBTC.Bitcoin.Validate()
if err != nil {
	if (bitcoin.Config{}) == config.Extensions.TBTC.Bitcoin {
		logger.Warnf("missing bitcoin configuration for tbtc extension: [%v]", err)
	} else {
		return err
	}
}
```

**Comment by beaushinkle** [comment]
Okay - got more tests added and everything's passing. I think this is ready for another round of review!

**Review by nkuba — CHANGES_REQUESTED** [review]

File: pkg/chain/bitcoin/derive_address_test.go [hunk 5]
```diff
@@ -171,158 +180,105 @@ func ErrorContains(err error, expected string) bool {
...
+			"5Hwgr3u458GLafKBgxtssHSPqJnYoGrSzgQsPwLFhLNYskDPyyA",
+			&chaincfg.MainNetParams,
+			"[5Hwgr3u458GLafKBgxtssHSPqJnYoGrSzgQsPwLFhLNYskDPyyA] is not a valid btc address using chain [mainnet]: [error parsing extended public key: [the provided serialized extended key length is invalid]]",
+		},
+		"testnet private key": {
+			"92Pg46rUhgTT7romnV7iGW6W1gbGdeezqdbJCzShkCsYNzyyNcc",
+			&chaincfg.TestNet3Params,
+			"[92Pg46rUhgTT7romnV7iGW6W1gbGdeezqdbJCzShkCsYNzyyNcc] is not a valid btc address using chain [testnet3]: [error parsing extended public key: [the provided serialized extended key length is invalid]]",
+		},
+	}
```
Comment (nkuba) [inline pkg/chain/bitcoin/derive_address_test.go:269]: Can we add a case where the address is testnet's address and chain params are for the mainnet?

File: pkg/chain/bitcoin/derive_address.go [hunk 6]
```diff
@@ -123,27 +122,21 @@ func deriveAddress(extendedPublicKey string, addressIndex uint32) (string, error
...
-	handle bitcoin.Handle,
-) (string, error) {
-	// If the address decodes without error, then we have a valid bitcoin
-	// address. Otherwise, we assume that it's an extended key and we attempt to
-	// derive the address.
-	_, err := btcutil.DecodeAddress(beneficiaryAddress, chainParams)
+// ValidateAddress checks to see if the supplied btc address is valid on the
+// supplied chain. We check both raw btc addresses and *pub extended keys.
+func ValidateAddress(btcAddress string, chainParams *chaincfg.Params) error {
+	_, err := btcutil.DecodeAddress(btcAddress, chainParams)
```
Comment (nkuba) [inline pkg/chain/bitcoin/derive_address.go:128]: We coul validate the address for chain like this:
```go
	decodedAddress, err := btcutil.DecodeAddress(btcAddress, chainParams)
	if err != nil {
		...
	}

	if !decodedAddress.IsForNet(chainParams) {
		return fmt.Errorf(
			"provided address [%s] is not a valid btc address for chain [%s]",
			btcAddress,
			chain.Name(),
		)
	}
```

Comment (beaushinkle) [reply pkg/chain/bitcoin/derive_address.go:128]: Is there a case where the address will properly decode, but `IsForNet` will be false? Adding that in didn't change any of my test results (maybe there's a gap in the tests)

Comment (nkuba) [reply pkg/chain/bitcoin/derive_address.go:128]: Yes, it should fail if you provide e.g. mainnet address and testnet chain params

Comment (beaushinkle) [reply pkg/chain/bitcoin/derive_address.go:128]: I added some mismatched address/chain tests in da3b5ef9ce490e9643115d0a78a9698dde8dc8a9 that appear to be working, though the error message isn't the greatest

Comment (nkuba) [reply pkg/chain/bitcoin/derive_address.go:128]: btcutil.DecodeAddress is not using provided chain params to validate the address but it's using the chain params to generate an address in case it receives a public key.

Comment (beaushinkle) [reply pkg/chain/bitcoin/derive_address.go:128]: Sorry - to elaborate a little: 

`1MjCqoLqMZ6Ru64TTtP16XnpSdiE8Kpgcx` is a mainnet address.

If I run 
```go
btcutil.DecodeAddress("1MjCqoLqMZ6Ru64TTtP16XnpSdiE8Kpgcx", &chaincfg.TestNet3Params)
```
I get `error parsing extended public key: [the provided serialized extended key length is invalid]`

How do you want to handle that?

Comment (nkuba) [reply pkg/chain/bitcoin/derive_address.go:128]: What  do you think about including both errors in the final validation error message:
```go
func ValidateAddress(btcAddress string, chainParams *chaincfg.Params) error {
	decodedAddress, decodeErr := btcutil.DecodeAddress(btcAddress, chainParams)
	if decodeErr != nil {
		_, deriveErr := DeriveAddress(btcAddress, 0)
		if deriveErr != nil {
			return fmt.Errorf(
				"[%s] is not a valid btc address using chain [%s]: "+
					"decode address failed with [%v] and "+
					"derive address failed with [%v]",
				btcAddress,
				chainParams.Name,
				decodeErr,
				deriveErr,
			)
		}
		return nil
	}

	if !decodedAddress.IsForNet(chainParams) {
		return fmt.Errorf(
			"provided address [%s] is not a valid btc address for chain [%s]",
			btcAddress,
			chainParams.Name,
		)
	}

	return nil
}
```

**Comment by beaushinkle** [comment]
Good for another look!

**Review by nkuba — APPROVED** [review]
I left just one non-blocking question.

File: pkg/chain/bitcoin/derive_address_test.go [hunk 7]
```diff
@@ -143,6 +141,17 @@ func TestDeriveAddress(t *testing.T) {
 	}
 }
 
+func TestValidateAddress_ExtendedMainNextAddresses(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (beaushinkle) [reply pkg/chain/bitcoin/derive_address_test.go:144]: hah!
